### ISSUE TITLE
Failing for (127, 113, t=2) polynomial

### ISSUE THREAD

**Issue by robbie01** [jkent/python-bchlib#21]
I'm trying to use this library to provide the BCH coding used in the TPS data of DVB-T, as per the ETSI spec at https://www.etsi.org/deliver/etsi_en/300700_300799/300744/01.06.02_60/en_300744v010602p.pdf. I'm trying to use the t=2 polynomial `x^14 + x^9 + x^8 + x^6 + x^5 + x^4 + x^2 + x + 1` (rendered in binary as `0b100001101110111`) with the library, but I keep getting the error `RuntimeError: unable to inititalize BCH, bad parameters?`. How can I resolve this?

**Comment by jkent** [comment]
I'm not exactly sure how to solve this.  The error comes from init_bch in bch.c, which is magic to me.. I've tried different values of m and that didn't work either.  I also tried against PR #20 to no avail.  Sorry :(

**Comment by lolib11** [comment]
same error come with me ! 
can anyone help me to find the correct way to initialize the polynomial parameters to be suitable with different values of m and t ?!

**Comment by TheCrazyT** [comment]
So BCH_POLYNOMIAL would be 0x4377 (and BCH_BITS=2?).
I wonder if "bitswapping" is needed.(I once had nand-chip where nand-dump had bhc-encoding with 0x4377, but needed bitswapping)
In that case forget about using this library, the bch library seems to be too old for that.

Of course you can always get a newer version(bch.c,bch.h) from the linux kernel and modify it to work with this library.
(just compare with the bch.c in this repository ... there are some macros you need to define in order to avoid including kernel headers)

**Comment by jkent** [comment]
I'm open for discussion on changing the API.  Using kwargs would probably be best with sane defaults if they aren't specified.  I'll update the bch library to the latest kernel version as well.  @TheCrazyT do you wish to open a new issue for discussion?

**Comment by TheCrazyT** [comment]
@jkent no I'm fine with this issue for discussion.

**Comment by dj-on-github** [comment]
Something changed. I have code that used "bch = bchlib.BCH(0x43,7)" and it used to work fine. Now it gives the error above. See https://github.com/dj-on-github/pufattack .
